Repository EmoHiphopSeason2/mz2mo-server, pull requests merged in 2023-07, with the labels that each got.

#4 [MZO-15] CI 테스트용 GithubAction 파이프라인 작성
  .github/workflows/DEVELOP_TEST.yml
Labels: 🌏 Deploy, ⚙ Setting

#11 [MZO-15] CI 테스트용 GithubAction 파이프라인 오류 수정
  .github/workflows/DEVELOP_TEST.yml
Labels: 🐞 Bug, ✅ Test

#10 remove: CI/CD yml 파일 폴더 이동
  .github/workflows/DEVELOP_CICD.yml
Labels: 🐞 Bug
